require:
  - "rubocop-performance"
  - "rubocop-rspec"

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0

Layout/LineLength:
  Max: 80
  Exclude:
    - y-rb.gemspec
    - spec/y/bugs_spec.rb

Metrics/BlockLength:
  Exclude:
    - spec/y/*_spec.rb

RSpec/ExampleLength:
  Max: 10
  Exclude:
    - spec/y/bugs_spec.rb

RSpec/NoExpectationExample:
  Exclude:
    - spec/y/bugs_spec.rb

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes
